name: Lint webdriver_java
on:
  push:
    branches:
    - main
    paths:
    - 'webdriver_java/**'
  pull_request:
    branches:
    - main
    paths:
    - 'webdriver_java/**'

jobs:
  lint_webdriver_java:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2

      - name: Lint webdriver_java
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--dry-run --set-exit-if-changed"
