name: Test webdriver_python
on:
  push:
    branches:
    - main
    paths:
    - 'javascript/**'
    - 'webdriver_python/**'
  pull_request:
    branches:
    - main
    paths:
    - 'javascript/**'
    - 'webdriver_python/**'

jobs:
  test_webdriver_python:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - uses: abatilo/actions-poetry@v2.0.0

      - name: Test webdriver_python
        run: |
          cd webdriver_python
          poetry install
          ./scripts/test.sh
