name: Test webdriver_java
on:
  push:
    branches:
    - main
    paths:
    - 'javascript/**'
    - 'webdriver_java/**'
  pull_request:
    branches:
    - main
    paths:
    - 'javascript/**'
    - 'webdriver_java/**'

jobs:
  test_webdriver_java:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Test webdriver_java
        run: |
          cd webdriver_java
          mvn test
